locale                   : "en-US"
title                    : "Trust Bridge"
title_separator          : "|"
name                     : "Steven Capell"
description              : "Trust Bridge - Building Bridges with Secure Digital Administration"

teaser                   : /assets/img/trust-bridge-og-image.png



google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)



og_image                 :  /assets/img/trust-bridge-og-image.png # Open Graph/Twitter default site image

